// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vobkfalffhihixfmaezo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvYmtmYWxmZmhpaGl4Zm1hZXpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjg5MTUsImV4cCI6MjA2ODc0NDkxNX0.cPxSdgh4f1Qg5qTpCBD4n8cQ91MNMWp_McBebxIlbHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});